### ISSUE TITLE
compose.yaml - fehlender Eintrag 'driver: json-file' führt zu Fehler beim Start von ingest

### ISSUE THREAD

**Issue by e862** [solectrus/ingest#14]
Mit der compose.yaml für den Test von ingest bekomme ich diesen Fehler:

> Error response from daemon: unknown log opt 'max-size' for journald log driver

Könntest du bitte im `ingest:` Abschnitt des **compose.yaml** Beispiels noch die Zeile `driver: json-file` einfügen?
Dann ist der Fehler weg.

```
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

```
Danke sehr!
